; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.1.3-LPC-1 on Tue Aug 18 2020 11:31:44 GMT+0200 (czas środkowoeuropejski letni)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


