; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.1.3-LPC-1 on Tue Aug 18 2020 11:31:45 GMT+0200 (czas środkowoeuropejski letni)
; Wait for set temperatures to be reached
M116 P0

